### ISSUE TITLE
Burrow clone creates symlink when clone is used within gopath

### ISSUE THREAD

**Issue by martin31821** [EmbeddedEnterprises/burrow#2]
Burrow should catch clones within the gopath.

**Comment by fin-ger** [comment]
This is not a bug. This is intended behavior. Have a look in the manual which states:

```
clone                  Clone a git repository into your GOPATH and create a symbolic link in your current location.
```

However, we can think about changing the behavior of `clone` to also work inside the GOPATH. If this is desired, please add the `enhancement` label. For now I will close this issue.

**Comment by fin-ger** [comment]
Decided to add as feature.
