### ISSUE TITLE
burrow init fails upon encountering '-' in project name

### ISSUE THREAD

**Issue by bengsparks** [EmbeddedEnterprises/burrow#7]
Problem: `burrow init` fails when building `an initial list of packages to scan` if the project name contains a hyphen.

Error: `Failed to build an initial list of packages to scan: expected 'IDENT', found 'go'`

Example: 
```
Is your project a binary (bin) or a library (lib)? lib
What is the name of your project? go-get-science
Which license (SPDX License or none) should your project use? none
Please enter a description of your project: Go implementation of the kRPC API for Kerbal Space Program
Please enter a comma-separated list of the authors of this project:
Benjamin Sparks, Johannes Wuensche
```

@fin-ger

**Comment by martin31821** [comment]
As far as I can tell, this is a problem with the lib template, because burrow just places the project name within the `package $projectname` which causes glide to fail, because dashes aren't allowed within package names.

**Comment by fin-ger** [comment]
Invalid as projects are no longer stored in gopath. See `burrow migrate`
